### ISSUE TITLE
zmq related exception

### ISSUE THREAD

**Issue by felixge** [piratefsh/image-processing-101#1]
Hi,

thanks for this amazing tutorial.

I just tried following the install instructions from the readme, and got the error below when trying to run `ipython notebook`.

It looks zmq related, so I tried `brew install zmq` and recreated the virtual env, but that didn't help.

Let me know if you any ideas.

Thanks
Felix

```
$ ipython notebook
Traceback (most recent call last):
  File "/Users/felix/code/image-processing-101/.venv/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/notebook/notebookapp.py", line 32, in <module>
    from zmq.eventloop import ioloop
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/cython/error.so, 2): Symbol not found: __ZNKSs4findEPKcm
  Referenced from: /Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/cython/error.so
  Expected in: flat namespace
 in /Users/felix/code/image-processing-101/.venv/lib/python2.7/site-packages/zmq/backend/cython/error.so
```

**Comment by piratefsh** [comment]
hey! sorry for taking some time to get back -- i haven't encountered this error, and Googling for "Expected in: flat namespace zmq" yielded this: https://github.com/zeromq/pyzmq/issues/582 issue. Hopefully that would help!
